CREATE PROCEDURE rdh_ImportSAPBOM_TotalList_Sirius

AS

SELECT FK_FileImportID, MATERIAL_HEADER, COUNT(*) Counting
INTO #tempBOM
FROM dbo.SAP_BOM as sb
WHERE MATERIAL_HEADER NOT IN (SELECT MATERIAL_HEADER FROM dbo.SAP_BOM_ManualLoadCorrections as sbmlc)
GROUP BY FK_FileImportID, MATERIAL_HEADER

SELECT MATERIAL_HEADER, MAX(FK_FileImportID) MaxFileImportID
INTO #tempBom2
FROM #tempBOM as tb
WHERE Counting > 1 
GROUP BY MATERIAL_HEADER

INSERT INTO #tempBom2 (MATERIAL_HEADER, MaxFileImportID)
SELECT DISTINCT MATERIAL_HEADER, -1
FROM dbo.SAP_BOM_ManualLoadCorrections as sbmlc
WHERE MATERIAL_HEADER NOT IN (SELECT MATERIAL_HEADER FROM #tempBom2 as tb)

INSERT INTO #tempBom2 (MATERIAL_HEADER, MaxFileImportID)
SELECT MATERIAL_HEADER, MAX(FK_FileImportID) MaxFileImportID
FROM #tempBOM as tb
WHERE MATERIAL_HEADER NOT IN (SELECT MATERIAL_HEADER FROM #tempBom2 as tb2)
GROUP BY tb.MATERIAL_HEADER

TRUNCATE TABLE dbo.SAP_BOM_TotalList

INSERT INTO dbo.SAP_BOM_TotalList
        ( FK_FileImportID ,
          MATERIAL_HEADER ,
          TYPE ,
          MATERIAL_COMPONENT ,
          ZUN
        )
SELECT MaxFileImportID, ISNULL(sb.MATERIAL_HEADER, sbmlc.MATERIAL_HEADER) MATERIAL_HEADER, 
	ISNULL(sb.TYPE, sbmlc.TYPE) TYPE, 
	ISNULL(sb.MATERIAL_COMPONENT, sbmlc.MATERIAL_COMPONENT) MATERIAL_COMPONENT, 
	ISNULL(sb.ZUN, sbmlc.ZUN) ZUN
FROM dbo.SAP_BOM as sb
	RIGHT JOIN #tempBom2 as tb ON sb.MATERIAL_HEADER = tb.MATERIAL_HEADER
		AND FK_FileImportID = MaxFileImportID
	LEFT JOIN dbo.SAP_BOM_ManualLoadCorrections as sbmlc ON tb.MATERIAL_HEADER = sbmlc.MATERIAL_HEADER
		AND MaxFileImportID = -1
