CREATE PROCEDURE rdh_ImportBOM_ManualLoadCorrections 

AS 

DECLARE @FileImportID INT 

SELECT @FileImportID = MAX(FK_FileImportID) FROM SAP_BOM 

INSERT INTO SAP_BOM ( FK_FileImportID, MATERIAL_HEADER, [TYPE], 
MATERIAL_COMPONENT, ZUN ) 
SELECT @FileImportID, MATERIAL_HEADER, [TYPE], 
MATERIAL_COMPONENT , ZUN 
FROM SAP_BOM_ManualLoadCorrections